### ISSUE TITLE
Signin flow

### ISSUE THREAD

**Issue by diCaminha** [gladguys/aluco-api#4]
The client needs to logged in on the API to make future requests and then the API verify who is the requester and what rights it has.

The client will request a POST with username and password.

### json
{
 	username: 'username',
	password: 'password'
}

### pre-requisite:
- At least 1 user registered on the database

### todo:
- check if there's an user with this email on the db
- generate token 
- send token on Http header response

### expected results:
- The user will request login and receive a response 200 with the token
- By the next request, with the token, the user will be already authenticated into the system

**Comment by lailsonbento** [comment]
Atividade concluída.
