### ISSUE TITLE
CRUD Student

### ISSUE THREAD

**Issue by diCaminha** [gladguys/aluco-api#7]
STUDENT | GET | /api/students | get all the students for a teacher (got by token) | - | [     {     "id": 2,     "name": "Gisela Martins",     "email": null,     "photoUrl": null,     "dateBirth": null,"phone":null,     "gender": 1,     "responsibleName": null,     "responsiblePhone": null,     "address": null,     "previousSchool": null,     "observation": null     },     {     "id": 34,     "name": "Joao Martins",     "email": null,     "photoUrl": null,     "dateBirth": null,"phone":null,     "gender": 1,     "responsibleName": null,     "responsiblePhone": null,     "address": null,     "previousSchool": null,     "observation": null     },     ]
-- | -- | -- | -- | -- | --
STUDENT | POST | /api/students | save a new student. | {     "name":   "Gisela Martins",     "email": "gisela@gmail.com",     "photoUrl": null,     "dateBirth":   "1993-04-11",     "phone": "85997802757",     "gender":   1,     "responsibleName": "Teresa Cristina",     "responsiblePhone": "67554433212",     "address": "Rua Evaristo da veiga 889",     "previousSchool": "Santo Inacio",     "observation": "a obs here"     } | {     "id": 2,     "name": "Gisela Martins",     "email": "gisela@gmail.com",     "photoUrl": null,     "dateBirth": "1993-04-11",     "phone": "85997802757",     "gender": 1,     "responsibleName": "Teresa Cristina",     "responsiblePhone": "67554433212",     "address": "Rua Evaristo da veiga 889",     "previousSchool": "Santo Inacio",     "observation": "a obs here"     }
STUDENT | GET | api/students/:id | get a speficif student by id | - | {     "id": 2,     "name": "Gisela Martins",     "email": "gisela@gmail.com",     "photoUrl": null,     "dateBirth": "1993-04-11",     "phone": "85997802757",     "gender": 1,     "responsibleName": "Teresa Cristina",     "responsiblePhone": "67554433212",     "address": "Rua Evaristo da veiga 889",     "previousSchool": "Santo Inacio",     "observation": "a obs here"     }
STUDENT | PUT | /api/students | update a student | {     "id": 2,     "name":   "Gisela Martins",     "email": "gisela@gmail.com",     "photoUrl": null,     "dateBirth":   "1993-04-11",     "phone": "85997802757",     "gender":   1,     "responsibleName": "Teresa Cristina",     "responsiblePhone": "67554433212",     "address": "Rua Evaristo da veiga 889",     "previousSchool": "Santo Inacio",     "observation": "a obs here"     } | {     "id": 2,     "name": "Gisela Martins",     "email": "gisela@gmail.com",     "photoUrl": null,     "dateBirth": "1993-04-11",     "phone": "85997802757",     "gender": 1,     "responsibleName": "Teresa Cristina",     "responsiblePhone": "67554433212",     "address": "Rua Evaristo da veiga 889",     "previousSchool": "Santo Inacio",     "observation": "a obs here"     }

**Comment by lailsonbento** [comment]
Crud implementado
